### ISSUE TITLE
Don't copy devDependencies

### ISSUE THREAD

**Issue by kopertop** [graphcool/serverless-plugin-typescript#13]
Currently, the code for this plugin copies the entire node_modules directory into the zip package. There are several packages (like this one) that don't need to be copied in there.

One solution would be to run ```npm install --production``` instead of copying in node_modules, but I don't think that's ideal as it takes time and doesn't necessarily copy the exact same modules that have been installed into node_modules. I'm not sure if just iterating over ```dependencies``` or ```devDependencies``` for specific inclusion or exclusion is good either.

**Comment by schickling** [comment]
Hmm that's a very good point. I'm also not aware of the best solution here. Maybe @pmuens had an idea?

**Comment by pmuens** [comment]
@schickling thanks for mentioning! 👍 

That's a pretty good point. We're already discussing a potential solution over here: https://github.com/serverless/serverless/issues/2709

This will be baked into Serverless core soon. Feel free to chime in!

**Comment by ProbablePrime** [comment]
The issue on serverless is closed but this still remains an issue here.

**Comment by pmuens** [comment]
@ProbablePrime thanks for reaching out 👍 

Unfortunately the solution we implemented included a bug where (in some circumstances) the packaging process skips some dev dependencies and doesn't exclude them properly. However we're currently working on a fix for that in the Framework code.

You can find the PR where we're working on the fix here: https://github.com/serverless/serverless/pull/3889

**Comment by schickling** [comment]
Thanks for the update @pmuens.

@kopertop @ProbablePrime I'll close this issue for now. In case serverless/serverless#3889 doesn't fix this, let's reopen this again.

**Comment by pmuens** [comment]
> Thanks for the update @pmuens.@kopertop @ProbablePrime I'll close this issue for now. In case serverless/serverless#3889 doesn't fix this, let's reopen this again.

Thanks for closing @schickling 👍 

**Quick update:** The fix should be ready soon and published in the upcoming version (which will be released next week).

**Comment by Alex0007** [comment]
serverless@1.18.0

```json
    "dependencies": {
        "aws-sdk": "^2.88.0",
        "cuid": "^1.3.8",
        "humps": "^2.0.1",
        "moment": "^2.18.1",
        "request": "^2.81.0"
    },
    "devDependencies": {
        "@types/aws-lambda": "0.0.15",
        "@types/cuid": "^1.3.0",
        "@types/humps": "^1.1.2",
        "@types/request": "^2.0.0",
        "serverless": "^1.18.0",
        "serverless-plugin-typescript": "^0.5.0",
        "tslint": "^5.5.0"
    }
```

For some reasons i have `typescript` bundled 

![image](https://user-images.githubusercontent.com/1143226/28545462-7ac5a1fc-70e0-11e7-94b5-80d0a9785cd7.png)

**Comment by pmuens** [comment]
Hey @Alex0007 thanks for the comment 👍!

Yes, unfortunately this is (yet another) bug with the dev dependency exclusion. More information can be found here: https://github.com/serverless/serverless/issues/3972 Lucky enough there's already a PR with a fix in the pipeline: https://github.com/serverless/serverless/pull/3975

For now you could opt-out of dev dependency exclusion with the help of this config:

```yml
package:
  excludeDevDependencies: false
```

https://serverless.com/framework/docs/providers/aws/guide/packaging/#development-dependencies

**Comment by keshavkaul** [comment]
@pmuens I'm still facing this issue. All my dev dependencies are included in final package
